pipeline:
  build:
    image: ubuntu:16.04
    commands:
      - ./ci/install-deps.sh
      - python run_test.py --storage fs
  slack:
    image: plugins/slack
    channel: integration-test
    username: drone
    secrets: [ slack_webhook  ]
    when:
        status: [ success, failure  ]
